import dotenv from "dotenv";
dotenv.config();
import express, { Express } from "express";
import { boatEndpoint } from "./routes/apiBoatEndpoint";
import "./utils/connect-db";
import bodyParser from "body-parser";
import { adminEndpoint } from "./routes/apiAdminEndpoint";
const app: Express = express();
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use("/api/boats", boatEndpoint);
app.use("/api/admin", adminEndpoint); 
app.listen(8080, () => console.log("Listening to 8080"));
